import { Roboto, Share_Tech, Play } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const play = Play({
  subsets: ["latin"],
  weight: "400",
});

const shareTech = Share_Tech({
  subsets: ["latin"],
  variable: "--font-share-tech",
  weight: "400",
});

export const Metadata = {
  title: "Alexander Aseme - Portfolio", 
  description: "Generated by create next app",
};

export {roboto, play, shareTech};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${shareTech.className} ${play.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
